server:
    port: ${PORT:8080}

spring:
    datasource:
        url: jdbc:postgresql://svc.sel4.cloudtype.app:32708/marathoners
        driver-class-name: org.postgresql.Driver
        username: root
        password: 1q2w3e4r!!
    sql:
        init:
            mode: always

    springdoc:
        api-docs:
            path: /api-docs
        swagger-ui:
            path: /swagger-ui.html

    logging:
        level:
            root: INFO
            com.project.marathon.repository: DEBUG  # MyBatis Repository
            org.mybatis: DEBUG                      # MyBatis
            org.apache.ibatis: TRACE                # MyBatis SQL
            org.springframework.security: DEBUG
    security:
        user:
            name: admin  # 기본 로그인 사용자
            password: admin  # 기본 비밀번호 (테스트 후 반드시 변경!)