server:
    port: ${PORT:8080}

spring:
    datasource:
        url: jdbc:postgresql://svc.sel4.cloudtype.app:32708/marathoners
        driver-class-name: org.postgresql.Driver
        username: root
        password: 1q2w3e4r!!
    sql:
        init:
            mode: always  # ?? SQL ???? ??

    springdoc:
        api-docs:
            path: /api-docs
        swagger-ui:
            path: /swagger-ui.html

    logging:
        level:
            root: INFO
            com.project.marathon.repository: DEBUG  # MyBatis Repository ?? ???
            org.mybatis: DEBUG                      # MyBatis ?? ?? ???
            org.apache.ibatis: TRACE                # MyBatis SQL ?? ?? ??
