server:
    port: ${PORT:8080}

spring:
    datasource:
        url: jdbc:p6spy:postgresql://svc.sel4.cloudtype.app:32708/marathoners
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # ✅ P6Spy 드라이버로 변경
        username: root
        password: 1q2w3e4r!!
    sql:
        init:
            mode: always

    springdoc:
        api-docs:
            path: /api-docs
        swagger-ui:
            path: /swagger-ui.html

    logging:
        level:
            root: INFO
            com.project.marathon.mapper: DEBUG  # MyBatis Repository
            org.mybatis: DEBUG                      # MyBatis
            org.apache.ibatis: TRACE                # MyBatis SQL
            org.springframework.security: DEBUG
            p6spy: DEBUG  # ✅ P6Spy의 SQL 로그 활성화

    security:
        user:
            name: admin  # 기본 로그인 사용자
            password: admin  # 기본 비밀번호 (테스트 후 반드시 변경!)

    # MyBatis 설정
    mybatis:
        mapper-locations: classpath:/mappers/**/*.xml  # 매퍼 XML 파일의 경로
        type-aliases-package: com.project.marathon.entity  # DTO 클래스 경로
        configuration:
            log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

decorator:
    datasource:
        p6spy:
            log-format: executionTime:%(executionTime) ms | sql:%(sql)
            enable-logging: 'true'
